import { ToolDefinition } from './types'

export const toolDefinitions: ToolDefinition[] = [
  {
    id: 'image-crop-rotate',
    name: 'Image Crop & Rotate',
    group: 'Image',
    icon: '/tools-icons/image crop.png',
    description: 'Visually crop a region and rotate the image (0°, 90°, 180°, 270°) with a live preview before exporting.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [],
    visualEditor: true,
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    group: 'Image',
    icon: '/tools-icons/image resize.png',
    description: 'Scale an image to exact width × height, or fit it inside a box keeping aspect ratio.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [
      { name: 'width', label: 'Width (px, 0 = auto)', type: 'number', default: 0, min: 0, step: 1 },
      { name: 'height', label: 'Height (px, 0 = auto)', type: 'number', default: 0, min: 0, step: 1 },
      { name: 'fit', label: 'Fit', type: 'select', options: ['stretch', 'fit-inside'], default: 'stretch' },
      { name: 'algo', label: 'Algorithm', type: 'select', options: ['bicubic', 'lanczos', 'bilinear', 'nearest', 'area'], default: 'bicubic' },
    ],
  },
  {
    id: 'image-crop',
    name: 'Image Crop',
    group: 'Image',
    icon: '/tools-icons/image crop.png',
    description: 'Cut out a rectangular region (pixel offsets + size) from the source image.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [
      { name: 'left', label: 'Left offset (px)', type: 'number', default: 0, min: 0, step: 1 },
      { name: 'top', label: 'Top offset (px)', type: 'number', default: 0, min: 0, step: 1 },
      { name: 'width', label: 'Crop width (px)', type: 'number', default: 0, min: 1, step: 1 },
      { name: 'height', label: 'Crop height (px)', type: 'number', default: 0, min: 1, step: 1 },
    ],
  },
  {
    id: 'image-compress',
    name: 'Image Compressor',
    group: 'Image',
    icon: '/tools-icons/image compressor.png',
    description: 'Shrink an image by lowering quality and/or switching to a more compact format.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [
      { name: 'format', label: 'Format', type: 'select', options: ['auto', 'jpg', 'png', 'webp'], default: 'auto' },
      { name: 'quality', label: 'Quality (1-100, higher = better)', type: 'number', default: 80, min: 1, max: 100, step: 1 },
    ],
  },
  {
    id: 'image-convert',
    name: 'Image Format Converter',
    group: 'Image',
    icon: '/tools-icons/image format convert.png',
    description: 'Re-encode an image cleanly to JPG, PNG or WebP.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [
      { name: 'format', label: 'Output format', type: 'select', options: ['jpg', 'png', 'webp'], default: 'png' },
      { name: 'quality', label: 'Quality (lossy formats)', type: 'number', default: 90, min: 1, max: 100, step: 1 },
    ],
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark / Overlay',
    group: 'Image',
    icon: '/tools-icons/add watermark.png',
    description: 'Overlay a graphic and/or text branding onto an image.',
    inputs: [
      { name: 'image', label: 'Base image', accept: 'image/*' },
      { name: 'watermark', label: 'Overlay image (optional)', accept: 'image/*', optional: true },
    ],
    fields: [
      { name: 'position', label: 'Position', type: 'select', options: ['center', 'top-left', 'top-right', 'bottom-left', 'bottom-right', 'top', 'bottom', 'left', 'right'], default: 'bottom-right' },
      { name: 'opacity', label: 'Overlay opacity (1-100)', type: 'number', default: 100, min: 1, max: 100, step: 1 },
      { name: 'scale', label: 'Overlay scale (% of image width)', type: 'number', default: 30, min: 10, max: 300, step: 5 },
      { name: 'text', label: 'Text label (optional)', type: 'text', default: '' },
      { name: 'fontSize', label: 'Font size (px)', type: 'number', default: 36, min: 8, max: 300, step: 1 },
      { name: 'color', label: 'Text color (hex)', type: 'text', default: 'FFFFFF' },
    ],
  },
  {
    id: 'image-strip-exif',
    name: 'EXIF Metadata Stripper',
    group: 'Image',
    icon: '/tools-icons/metadata stripper.png',
    description: 'Remove EXIF / camera-location / timestamp metadata. Re-encodes the image (PNG output is lossless).',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [
      { name: 'format', label: 'Output format', type: 'select', options: ['png', 'jpg', 'webp', 'keep'], default: 'png' },
    ],
  },
  {
    id: 'batch-rename',
    name: 'Batch Image Renamer',
    group: 'Image',
    icon: '/tools-icons/batch image renamer.png',
    description: 'Sanitize and rename many images at once — returns a ZIP of the renamed files.',
    inputs: [{ name: 'images', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'prefix', label: 'Prefix', type: 'text', default: '' },
      { name: 'suffix', label: 'Suffix', type: 'text', default: '' },
      { name: 'numbering', label: 'Numbering', type: 'select', options: ['none', 'seq'], default: 'seq' },
      { name: 'digits', label: 'Sequence digits', type: 'number', default: 2, min: 1, max: 6, step: 1 },
      { name: 'format', label: 'Format (keep = no re-encode)', type: 'select', options: ['keep', 'jpg', 'png', 'webp'], default: 'keep' },
      { name: 'quality', label: 'Quality when re-encoding', type: 'number', default: 90, min: 1, max: 100, step: 1 },
    ],
  },
  {
    id: 'image-album',
    name: 'Custom Album Creator',
    group: 'Image',
    icon: '/tools-icons/custom album creator.png',
    description: 'Lay multiple photos into a printable grid canvas (auto-aligned tiles).',
    inputs: [{ name: 'images', label: 'Photos', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'thumbW', label: 'Tile width (px)', type: 'number', default: 480, min: 32, step: 1 },
      { name: 'thumbH', label: 'Tile height (px)', type: 'number', default: 360, min: 32, step: 1 },
      { name: 'columns', label: 'Columns', type: 'number', default: 3, min: 1, max: 12, step: 1 },
      { name: 'spacing', label: 'Spacing (px)', type: 'number', default: 8, min: 0, step: 1 },
      { name: 'fit', label: 'Tile fit', type: 'select', options: ['stretch', 'cover'], default: 'stretch' },
      { name: 'color', label: 'Background color (hex)', type: 'text', default: '000000' },
      { name: 'format', label: 'Output format', type: 'select', options: ['png', 'jpg', 'webp'], default: 'png' },
    ],
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merger',
    group: 'PDF',
    icon: '/tools-icons/pdf merger.png',
    description: 'Combine several PDF files into a single document.',
    inputs: [{ name: 'pdf', label: 'PDF files', accept: 'application/pdf', multiple: true }],
    fields: [{ name: 'title', label: 'Document title (optional)', type: 'text', default: '' }],
  },
  {
    id: 'pdf-split',
    name: 'PDF Splitter',
    group: 'PDF',
    icon: '/tools-icons/pdf splitter.png',
    description: 'Extract page ranges (e.g. 1-3,5,7-9) into separate PDFs (returned as a ZIP).',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [{ name: 'ranges', label: 'Page ranges (1-based, comma separated)', type: 'text', default: '1-3' }],
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Page Rotator',
    group: 'PDF',
    icon: '/tools-icons/pdf page rotator.png',
    description: 'Rotate all pages (or a single page) by 90° / 180° / 270°.',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [
      { name: 'degrees', label: 'Rotation', type: 'select', options: ['90', '180', '270'], default: '90' },
      { name: 'all', label: 'Apply to', type: 'select', options: ['all-pages', 'single-page'], default: 'all-pages' },
      { name: 'page', label: 'Page number (if single)', type: 'number', default: 1, min: 1, step: 1 },
    ],
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    group: 'PDF',
    icon: '/tools-icons/image to pdf.png',
    description: 'Turn one or more images into a PDF with one image per page.',
    inputs: [{ name: 'images', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [],
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compressor',
    group: 'PDF',
    icon: '/tools-icons/pdf compressor.png',
    description: 'Shrink a PDF by re-normalizing it with compressed object streams.',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [],
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    group: 'PDF',
    icon: '/tools-icons/pdf to image.png',
    description: 'Render each PDF page to PNG or JPG in the browser (returned as a ZIP).',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [
      { name: 'format', label: 'Image format', type: 'select', options: ['png', 'jpg'], default: 'png' },
      { name: 'dpi', label: 'Resolution (DPI)', type: 'number', default: 150, min: 50, max: 300, step: 10 },
    ],
  },
]

export const toolsByGroup = (group: 'Image' | 'PDF'): ToolDefinition[] =>
  toolDefinitions.filter((tool) => tool.group === group)

export const getToolById = (id: string): ToolDefinition | undefined =>
  toolDefinitions.find((tool) => tool.id === id)