import { ToolDefinition } from './types'

export const toolDefinitions: ToolDefinition[] = [
  {
    id: 'image-convert',
    name: 'Image Format Converter',
    group: 'Image',
    icon: '/tools-icons/image format convert.png',
    description: 'Re-encode one or more images cleanly to JPG, PNG, WebP, GIF, BMP, AVIF or ICO — results download individually or as a ZIP.',
    inputs: [{ name: 'image', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'format', label: 'Output format', type: 'select', options: ['jpg', 'png', 'webp', 'gif', 'bmp', 'avif', 'ico'], default: 'png' },
      { name: 'quality', label: 'Quality (JPG / WebP / AVIF only)', type: 'number', default: 90, min: 1, max: 100, step: 1 },
    ],
  },
  {
    id: 'image-compress',
    name: 'Image Compressor',
    group: 'Image',
    icon: '/tools-icons/image compressor.png',
    description: 'Compress one or more images by quality percentage or target file size — results download individually or as a ZIP.',
    inputs: [{ name: 'image', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'mode', label: 'Compression mode', type: 'select', options: ['percentage', 'targetSize'], default: 'percentage' },
      { name: 'quality', label: 'Quality % (JPG/WebP/PNG)', type: 'number', default: 75, min: 1, max: 100, step: 1, visibleWhen: { field: 'mode', equals: 'percentage' } },
      { name: 'targetSize', label: 'Target size', type: 'number', default: 500, min: 1, step: 1, visibleWhen: { field: 'mode', equals: 'targetSize' } },
      { name: 'targetUnit', label: 'Target unit', type: 'select', options: ['KB', 'MB'], default: 'KB', visibleWhen: { field: 'mode', equals: 'targetSize' } },
      { name: 'format', label: 'Output format', type: 'select', options: ['auto', 'jpg', 'png', 'webp'], default: 'auto' },
    ],
  },
  {
    id: 'image-background-erase',
    name: 'Background Eraser',
    group: 'Image',
    icon: '/tools-icons/bg remover.png',
    description: 'Erase photo backgrounds with a real AI matting model that runs 100% on your device — nothing is ever uploaded.',
    inputs: [{ name: 'image', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'model', label: 'AI model', type: 'select', options: ['medium (best quality)', 'small (fastest)'], default: 'medium (best quality)' },
      { name: 'background', label: 'New background', type: 'select', options: ['transparent', 'white', 'black', 'custom color'], default: 'transparent' },
      { name: 'backgroundColor', label: 'Custom color', type: 'color', default: '#FFFFFF', visibleWhen: { field: 'background', equals: 'custom color' } },
      { name: 'outputFormat', label: 'Output format', type: 'select', options: ['png', 'webp'], default: 'png' },
    ],
  },
  {
    id: 'image-crop-rotate',
    name: 'Image Crop & Rotate',
    group: 'Image',
    icon: '/tools-icons/image crop.png',
    description: 'Visually crop a region and rotate the image (0°, 90°, 180°, 270°) with a live preview before exporting.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [],
    visualEditor: true,
    editor: 'crop-rotate',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark / Overlay',
    group: 'Image',
    icon: '/tools-icons/add watermark.png',
    description: 'Overlay a graphic and/or text branding onto an image — pick any font and color for the text.',
    inputs: [
      { name: 'image', label: 'Base image', accept: 'image/*' },
      { name: 'watermark', label: 'Overlay image (optional)', accept: 'image/*', optional: true },
    ],
    fields: [
      { name: 'position', label: 'Position', type: 'select', options: ['center', 'top-left', 'top-right', 'bottom-left', 'bottom-right', 'top', 'bottom', 'left', 'right'], default: 'bottom-right' },
      { name: 'opacity', label: 'Overlay opacity (1-100)', type: 'number', default: 100, min: 1, max: 100, step: 1 },
      { name: 'scale', label: 'Overlay scale (% of image width)', type: 'number', default: 30, min: 10, max: 300, step: 5 },
      { name: 'text', label: 'Text label (optional)', type: 'text', default: '' },
      { name: 'font', label: 'Font', type: 'font', options: ['Arial', 'Verdana', 'Tahoma', 'Trebuchet MS', 'Impact', 'Georgia', 'Times New Roman', 'Courier New', 'Comic Sans MS', 'Palatino Linotype'], default: 'Arial' },
      { name: 'fontSize', label: 'Font size (px)', type: 'number', default: 36, min: 8, max: 300, step: 1 },
      { name: 'color', label: 'Text color', type: 'color', default: '#FFFFFF' },
    ],
  },
  {
    id: 'image-adjust',
    name: 'Adjustments & Enhancement',
    group: 'Image',
    icon: '/tools-icons/adjustment & enhancement .png',
    description: 'One-pass photo tune-up — brightness, contrast, saturation, hue, color temperature, sharpening, blur, sepia and grayscale.',
    inputs: [{ name: 'image', label: 'Image files', accept: 'image/*', multiple: true }],
    livePreview: true,
    fields: [
      { name: 'brightness', label: 'Brightness', type: 'range', default: 0, min: -100, max: 100, step: 1 },
      { name: 'contrast', label: 'Contrast', type: 'range', default: 0, min: -100, max: 100, step: 1 },
      { name: 'saturation', label: 'Saturation', type: 'range', default: 0, min: -100, max: 100, step: 1 },
      { name: 'temperature', label: 'Temperature', type: 'range', default: 0, min: -100, max: 100, step: 1 },
      { name: 'hue', label: 'Hue rotate', type: 'range', default: 0, min: -180, max: 180, step: 1 },
      { name: 'sharpen', label: 'Sharpen', type: 'range', default: 0, min: 0, max: 100, step: 1 },
      { name: 'blur', label: 'Blur', type: 'range', default: 0, min: 0, max: 50, step: 0.5 },
      { name: 'sepia', label: 'Sepia', type: 'range', default: 0, min: 0, max: 100, step: 1 },
      { name: 'grayscale', label: 'Grayscale', type: 'range', default: 0, min: 0, max: 100, step: 1 },
      { name: 'format', label: 'Output format', type: 'select', options: ['keep', 'png', 'jpg', 'webp'], default: 'keep' },
    ],
  },
  {
    id: 'image-album',
    name: 'Custom Album Creator',
    group: 'Image',
    icon: '/tools-icons/custom album creator.png',
    description: 'Design a photo album visually — pick a template (grid, polaroid, film strip and more), style it, and preview it live.',
    inputs: [{ name: 'images', label: 'Photos', accept: 'image/*', multiple: true }],
    fields: [],
    visualEditor: true,
    editor: 'album',
  },
  {
    id: 'image-flip',
    name: 'Image Flip / Mirror',
    group: 'Image',
    icon: '/tools-icons/flip image.png',
    description: 'Mirror one or more images horizontally or vertically (or both) — transparency is preserved and the output format is up to you.',
    inputs: [{ name: 'image', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'direction', label: 'Flip direction', type: 'select', options: ['horizontal', 'vertical', 'both'], default: 'horizontal' },
      { name: 'format', label: 'Output format', type: 'select', options: ['keep', 'png', 'jpg', 'webp'], default: 'keep' },
    ],
  },
  {
    id: 'image-strip-exif',
    name: 'EXIF Metadata Stripper',
    group: 'Image',
    icon: '/tools-icons/metadata stripper.png',
    description: 'Remove EXIF / camera-location / timestamp metadata. Re-encodes the image (PNG output is lossless).',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [
      { name: 'format', label: 'Output format', type: 'select', options: ['png', 'jpg', 'webp', 'keep'], default: 'png' },
    ],
  },
  {
    id: 'image-resize',
    name: 'Image Resize',
    group: 'Image',
    icon: '/tools-icons/image resize.png',
    description: 'Visually rescale an image, exact size or fit-inside box, with aspect-ratio lock and a live preview.',
    inputs: [{ name: 'image', label: 'Image file', accept: 'image/*' }],
    fields: [],
    visualEditor: true,
    editor: 'resize',
  },
  {
    id: 'batch-rename',
    name: 'Batch Image Renamer',
    group: 'Image',
    icon: '/tools-icons/batch image renamer.png',
    description: 'Sanitize and rename many images at once — returns a ZIP of the renamed files.',
    inputs: [{ name: 'images', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [
      { name: 'prefix', label: 'Prefix', type: 'text', default: '' },
      { name: 'suffix', label: 'Suffix', type: 'text', default: '' },
      { name: 'numbering', label: 'Numbering', type: 'select', options: ['none', 'seq'], default: 'seq' },
      { name: 'digits', label: 'Sequence digits', type: 'number', default: 2, min: 1, max: 6, step: 1 },
      { name: 'format', label: 'Format (keep = no re-encode)', type: 'select', options: ['keep', 'jpg', 'png', 'webp'], default: 'keep' },
      { name: 'quality', label: 'Quality when re-encoding', type: 'number', default: 90, min: 1, max: 100, step: 1 },
    ],
  },
    {
    id: 'base64-converter',
    name: 'Base64 Converter',
    group: 'Image',
    icon: '/tools-icons/base64 converter.png',
    description: 'Encode images into Base64 (data URI or raw) for HTML/CSS embedding, or decode a Base64 / data-URI text file back into its original file.',
    inputs: [
      { name: 'image', label: 'Image files', accept: 'image/*', multiple: true, optional: true, visibleWhen: { field: 'mode', equals: 'encode' } },
      { name: 'text', label: 'Base64 text file', accept: '.txt,.b64,.base64,text/plain', optional: true, visibleWhen: { field: 'mode', equals: 'decode' } },
    ],
    fields: [
      { name: 'mode', label: 'Mode', type: 'select', options: ['encode', 'decode'], default: 'encode', position: 'top' },
      { name: 'output', label: 'Encoded output', type: 'select', options: ['data-uri', 'raw base64'], default: 'data-uri', visibleWhen: { field: 'mode', equals: 'encode' } },
    ],
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compressor',
    group: 'PDF',
    icon: '/tools-icons/pdf compressor.png',
    description: 'Compress one or more PDFs by quality percentage or target file size — results download individually or as a ZIP.',
    inputs: [{ name: 'pdf', label: 'PDF files', accept: 'application/pdf', multiple: true }],
    fields: [
      { name: 'mode', label: 'Compression mode', type: 'select', options: ['percentage', 'targetSize'], default: 'percentage' },
      { name: 'quality', label: 'Quality % (1-100)', type: 'number', default: 60, min: 1, max: 100, step: 1, visibleWhen: { field: 'mode', equals: 'percentage' } },
      { name: 'targetSize', label: 'Target size', type: 'number', default: 500, min: 1, step: 1, visibleWhen: { field: 'mode', equals: 'targetSize' } },
      { name: 'targetUnit', label: 'Target unit', type: 'select', options: ['KB', 'MB'], default: 'KB', visibleWhen: { field: 'mode', equals: 'targetSize' } },
    ],
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    group: 'PDF',
    icon: '/tools-icons/image to pdf.png',
    description: 'Turn one or more images into a PDF with one image per page.',
    inputs: [{ name: 'images', label: 'Image files', accept: 'image/*', multiple: true }],
    fields: [],
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    group: 'PDF',
    icon: '/tools-icons/pdf to image.png',
    description: 'Render each PDF page to PNG or JPG in the browser. Preview every page inline, then download individually or as a ZIP.',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [
      { name: 'format', label: 'Image format', type: 'select', options: ['png', 'jpg'], default: 'png' },
      { name: 'dpi', label: 'Resolution (DPI)', type: 'number', default: 150, min: 50, max: 300, step: 10 },
    ],
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    group: 'PDF',
    icon: '/tools-icons/pdf watermark.png',
    description: 'Stamp a logo image and/or text onto every page — 9 position anchors, opacity, scale, font and color. The original text stays selectable.',
    inputs: [
      { name: 'pdf', label: 'PDF file', accept: 'application/pdf' },
      { name: 'watermark', label: 'Watermark image (optional)', accept: 'image/*', optional: true },
    ],
    fields: [
      { name: 'position', label: 'Position', type: 'select', options: ['center', 'top-left', 'top-right', 'bottom-left', 'bottom-right', 'top', 'bottom', 'left', 'right'], default: 'bottom-right' },
      { name: 'opacity', label: 'Watermark opacity (1-100)', type: 'number', default: 100, min: 1, max: 100, step: 1 },
      { name: 'scale', label: 'Overlay scale (% of page width)', type: 'number', default: 30, min: 10, max: 300, step: 5 },
      { name: 'text', label: 'Text label (optional)', type: 'text', default: '' },
      { name: 'font', label: 'Font', type: 'font', options: ['Arial', 'Verdana', 'Tahoma', 'Trebuchet MS', 'Impact', 'Georgia', 'Times New Roman', 'Courier New', 'Comic Sans MS', 'Palatino Linotype'], default: 'Arial' },
      { name: 'fontSize', label: 'Font size (pt)', type: 'number', default: 36, min: 8, max: 300, step: 1 },
      { name: 'color', label: 'Text color', type: 'color', default: '#FFFFFF' },
    ],
  },
  {
    id: 'pdf-protect',
    name: 'Protect PDF',
    group: 'PDF',
    icon: '/tools-icons/pdf password protect.png',
    description: 'Lock a PDF with a password (AES-256 by default) and choose what readers may do — printing, copying, editing. Add an owner password for admin permissions.',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [
      { name: 'password', label: 'Password to open (user password)', type: 'password', default: '' },
      { name: 'ownerPassword', label: 'Owner password (optional — has all permissions)', type: 'password', default: '' },
      { name: 'algorithm', label: 'Encryption', type: 'select', options: ['AES-256', 'RC4'], default: 'AES-256' },
      { name: 'restrictions', label: 'Permissions for the password holder', type: 'select', options: ['no restrictions', 'prevent printing', 'view only'], default: 'no restrictions' },
    ],
  },
  {
    id: 'pdf-unlock',
    name: 'Unlock PDF',
    group: 'PDF',
    icon: '/tools-icons/unlock pdf.png',
    description: 'Remove the password from a protected PDF while keeping text selectable — enter the user or owner password to unlock it.',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [{ name: 'password', label: 'Password (leave blank if you believe the file has none)', type: 'password', default: '' }],
  },
{
    id: 'pdf-split',
    name: 'PDF Splitter',
    group: 'PDF',
    icon: '/tools-icons/pdf splitter.png',
    description: 'Extract page ranges (e.g. 1-3,5,7-9) into separate PDFs (returned as a ZIP).',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [{ name: 'ranges', label: 'Page ranges (1-based, comma separated)', type: 'text', default: '1-3' }],
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merger',
    group: 'PDF',
    icon: '/tools-icons/pdf merger.png',
    description: 'Combine several PDF files into a single document.',
    inputs: [{ name: 'pdf', label: 'PDF files', accept: 'application/pdf', multiple: true }],
    fields: [{ name: 'title', label: 'Document title (optional)', type: 'text', default: '' }],
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Page Rotator',
    group: 'PDF',
    icon: '/tools-icons/pdf page rotator.png',
    description: 'Rotate pages by 90deg / 180deg / 270deg. Use page ranges like 1-3,5,7-9 - or leave blank to rotate every page.',
    inputs: [{ name: 'pdf', label: 'PDF file', accept: 'application/pdf' }],
    fields: [
      { name: 'degrees', label: 'Rotation', type: 'select', options: ['90', '180', '270'], default: '90' },
      { name: 'pages', label: 'Pages (e.g. 1-3,5,7-9)', type: 'text', default: 'all' },
    ],
  },
]

export const toolsByGroup = (group: 'Image' | 'PDF'): ToolDefinition[] =>
  toolDefinitions.filter((tool) => tool.group === group)

export const getToolById = (id: string): ToolDefinition | undefined =>
  toolDefinitions.find((tool) => tool.id === id)
